import Head from 'next/head';
import Image from 'next/image';
import MockComponent from '@/components/MockComponent';
import Sidebar from '@/components/global/Sidebar';
import Topbar from '@/components/global/Topbar';
import { ColorModeContext, useMode } from '@/ui/theme';
import { CssBaseline, ThemeProvider } from '@mui/material';

export default function Home() {
  return (
    const [theme, colorMode] = useMode();
    <>
      <Head>
        <title>Dasbhoard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ColorModeContext.Provider value={colorMode}>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <div className='app'>
          <Sidebar />
          <main className="content">
            <Topbar />
            <MockComponent />
          </main>
        </div>
      </ThemeProvider>
    </ColorModeContext.Provider>
    </>
  )
}
